# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-app-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: note-app-frontend
  template:
    metadata:
      labels:
        app: note-app-frontend
    spec:
      containers:
        - name: note-frontend
          image: saipreetham7/note-app-frontend
          ports:
            - containerPort: 80
      #     volumeMounts:
      #       - name: static-files-storage
      #         mountPath: /usr/share/nginx/html
      # volumes:
      #   - name: static-files-storage
      #     persistentVolumeClaim:
      #       claimName: static-files-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: note-app-frontend
spec:
  selector:
    app: note-app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
