# static-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-files-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/mnt/static-files'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-files-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
